services:
  - type: web
    name: tanstack-start-ssr
    runtime: node
    buildCommand: "npm install && npm run build"
    startCommand: "node .output/server/index.mjs"
    envVars:
      NODE_VERSION: 20
